### ISSUE TITLE
Not working, pls help

### ISSUE THREAD

**Issue by WhiteAnon1** [Rdimo/Hazard-Token-Grabber#12]
i have done build, but he's not working, he doesn't send token on my discord, idk why ?
i click two times on build, but i see he is not starting

**Comment by addi00000** [comment]
Use hazard v2

**Comment by Straight12** [comment]
ye

**Comment by WhiteAnon1** [comment]
i wrote in the wrong place, i use hazard v2

**Comment by Straight12** [comment]
oh
